--Basic
require('core.plugins')
require('core.mappings')
require('core.configs')
--Plugins
require('plugins.hop')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.nullls')
require('plugins.lualine')
require('plugins.indentblankline')
require('plugins.barbar')
require('plugins.catppuccin')
